### ISSUE TITLE
BUCKET_SIZE meaning?

### ISSUE THREAD

**Issue by xilinniao123** [iwangjian/ByteCup2018#3]
BUCKET_SIZE means batch_size?

**Comment by iwangjian** [comment]
BUCKET_SIZE can be viewed as the batch size just for data loader, it's not the training batch_size.

**Comment by xilinniao123** [comment]
thanks for answering，if i set the  parameter  of dataloader(batch_size   equals to training batch_size,is it ok?

**Comment by iwangjian** [comment]
yes, of course.
